### ISSUE TITLE
[ADD] handle errors

### ISSUE THREAD

**Issue by ricardogcolombo** [labs-js/turbo-commit#16]
Using turbo commit on a folder that not correspond to a git repository throws an error in terminal.

? Select tag for your turbo-commit [ADD] : features commits, adding lines of code
exec error: ${error} { Error: Command failed: git commit -m "[ADD] add"
fatal: Not a git repository (or any of the parent directories): .git

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:485:12)
```

  killed: false,
  code: 128,
  signal: null,
  cmd: 'git commit -m "[ADD] add"' }

**Comment by sfabrizio** [comment]
yep, we need to fix this.. and when we run `tc` we should see the command help instead nothing.

**Comment by alancampora** [comment]
Please, checkout error-handling branch, I've just pushed some changes.

**Comment by sfabrizio** [comment]
This was fixed already
